# model_config.yaml
# @author: wronk
# Specify the neural network architectures

arch: 
    - [1000, 1000, 'None']
    - [1000, 4000, 'None']
    - [4000, 1000, 'None']
    - [4000, 4000, 'None']

activation: 
    - 'relu'

dropout:
    - 0.0

optimizer:
    - 'adam'

loss:
    - 'mse'

metrics: 
    ['mse']

n_epochs:
    - 10000
